server:
  port: 1111

spring:
  application:
    name: facade-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defautZone: http://localhost:8761/eureka

