server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: facade-service
          uri: lb://user-service
          predicates:
            - Path=/users
        - id: facade-service
          uri: lb://exam-schedule-service
          predicates:
            - Path=/**
        - id: facade-service
          uri: lb://group-subject-service
          predicates:
            - Path=/**
        - id: facade-service
          uri: lb://facade-service
          predicates:
            - Path=/auth/login
            - Method=GET


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka