server:
  port: 0

spring:
  application:
    name: group-subject-service
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defautZone: http://localhost:8761/eureka

